### ISSUE TITLE
Unpin python-graphviz install for Windows CI tests

### ISSUE THREAD

**Issue by rwedge** [alteryx/featuretools#1289]
After installing the newest python-graphviz version via conda in our windows environment, we this stacktrace when checking to see that graphviz works:

```python-traceback
Traceback (most recent call last):
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\site-packages\graphviz\backend.py", line 166, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\site-packages\graphviz\files.py", line 171, in pipe
    quiet=quiet)
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\site-packages\graphviz\backend.py", line 250, in pipe
    out, _ = run(cmd, input=data, capture_output=True, check=True, quiet=quiet)
  File "C:\Users\runneradmin\Miniconda3\envs\featuretools\lib\site-packages\graphviz\backend.py", line 169, in run
    raise ExecutableNotFound(cmd)
graphviz.backend.ExecutableNotFound: failed to execute ['dot', '-Kdot.bat', '-Tpdf'], make sure the Graphviz executables are on your systems' PATH
```

**Comment by rwedge** [comment]
Looked into this issue for a bit, there's an issue with the latest version of the python graphviz library on conda forge.  Once that gets figured out we can unpin.
