### ISSUE TITLE
TypeError: Cannot perform reduction 'median' with string dtype

### ISSUE THREAD

**Issue by dehiker** [alteryx/featuretools#2346]
I split a huge data into chunks to do feature engineering. Basically, I called **ft.dfs** for the first chunk, and **saved features definition**, which was a dict with different training_windows as keys, **to a pickle file**; and then I loaded features definition back and called ft.calculate_feature_matrix for subsequent chunks.

Sadly, it didn't work as I expected:
1. ft.calculate_feature_matrix raised **TypeError for the 2nd chunk** as the issue title indicated
    From the stack info shown below, it seems we could not figure out which feature caused the error. Do you have any ideas on this? And can we ignore the erroneous features and procede with correct ones?
    <details>
    /home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py:812: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before callin
    g .agg, select only columns which should be valid for the function.
    to_merge = base_frame.groupby(
    2022-10-31 08:10:16,389 - distributed.worker - WARNING - Compute Failed
    Key:       calculate_chunk-e4aba6edc7d417440b253569a84ea03f
    Function:  execute_task
    args:      ((<function apply at 0x7f2c28d490d0>, <function calculate_chunk at 0x7f2c0b2b24c0>, (<class 'tuple'>, [        instance_id       time _ft_last_time
    191   CON2210012774 2022-10-03    2022-10-03
    192   CON2210013083 2022-10-03    2022-10-03
    193   CON2210013134 2022-10-03    2022-10-03
    194   CON2210015037 2022-10-03    2022-10-03
    195   CON2210016906 2022-10-03    2022-10-03
    196  CON22100211324 2022-10-03    2022-10-03
    197  CON22100211429 2022-10-03    2022-10-03
    198  CON22100212836 2022-10-03    2022-10-03
    199  CON22100214940 2022-10-03    2022-10-03
    200   CON2210021638 2022-10-03    2022-10-03
    201   CON2210021683 2022-10-03    2022-10-03
    202   CON2210021937 2022-10-03    2022-10-03
    203   CON2210022117 2022-10-03    2022-10-03
    204   CON2210022324 2022-10-03    2022-10-03
    205   CON2210022385 2022-10-03    2022-10-03
    206   CON2210023671 2022-10-03    2022-10-03
    207   CON2210024694 2022-10-03    2022-10-03
    208   CON2210025872 2022-10-03    2022-10-03
    209   CON2210027493 2022-10-03    2022-10-
    kwargs:    {}
    Exception: 'TypeError("Cannot perform reduction \'median\' with string dtype")'

    Traceback (most recent call last):
    File "/home/zzz/.conda/envs/test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
    File "/home/zzz/.conda/envs/test/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
    File "/home/zzz/python/xx-feas/xx-feas/ft.py", line 390, in <module>
        fire.Fire(ft_parsed_slik)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
        component_trace = _Fire(component, args, parsed_flag_args, context, name)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
        component, remaining_args = _CallAndUpdateTrace(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
        component = fn(*varargs, **kwargs)
    File "/home/zzz/python/xx-feas/xx-feas/ft.py", line 255, in ft_data
        feature_matrix_ = ft.calculate_feature_matrix(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 316, in calculate_feature_matrix
        feature_matrix = parallel_calculate_chunks(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 855, in parallel_calculate_chunks
        results = client.gather(batch)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/client.py", line 2174, in gather
        return self.sync(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 338, in sync
        return sync(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 405, in sync
        raise exc.with_traceback(tb)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/utils.py", line 378, in f
        result = yield future
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
        value = future.result()
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/distributed/client.py", line 2037, in _gather
        raise exception.with_traceback(traceback)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/dask/utils.py", line 41, in apply
        return func(*args, **kwargs)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 536, in calculate_chunk
        _feature_matrix = calc_results(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/utils.py", line 43, in wrapped
        r = method(*args, **kwargs)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/calculate_feature_matrix.py", line 506, in calc_results
        matrix = calculator.run(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 121, in run
        self._calculate_features_for_dataframe(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 365, in _calculate_features_for_dataframe
        df = self._calculate_features(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 385, in _calculate_features
        df = handler(group, df, df_trie, progress_callback)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/featuretools/computational_backends/feature_set_calculator.py", line 812, in _calculate_agg_features
        to_merge = base_frame.groupby(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 869, in aggregate
        result = op.agg()
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 168, in agg
        return self.agg_dict_like()
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 481, in agg_dict_like
        results = {
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/apply.py", line 482, in <dictcomp>
        key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 271, in aggregate
        ret = self._aggregate_multiple_funcs(func)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 326, in _aggregate_multiple_funcs
        results[key] = self.aggregate(func)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/generic.py", line 287, in aggregate
        return self._python_agg_general(func, *args, **kwargs)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1499, in _python_agg_general
        return self._python_apply_general(f, self._selected_obj)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1464, in _python_apply_general
        values, mutated = self.grouper.apply(f, data, self.axis)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/ops.py", line 761, in apply
        res = f(group)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/groupby/groupby.py", line 1476, in <lambda>
        f = lambda x: func(x, *args, **kwargs)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 11194, in median
        return NDFrame.median(self, axis, skipna, level, numeric_only, **kwargs)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 10706, in median
        return self._stat_function(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/generic.py", line 10646, in _stat_function
        return self._reduce(
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/series.py", line 4459, in _reduce
        return delegate._reduce(name, skipna=skipna, **kwds)
    File "/home/zzz/.conda/envs/test/lib/python3.9/site-packages/pandas/core/arrays/string_.py", line 461, in _reduce
        raise TypeError(f"Cannot perform reduction '{name}' with string dtype")
    TypeError: Cannot perform reduction 'median' with string dtype
    </details>

3. **Failed to load the pickle file of features definition** in another directory
    While I saved features definition in a module, I failed to load them back for ModuleNotFoundError, in which 'xx-feas' is my module name. Anybody has ideas why saving definitions had any relation with the module? And what would be a better way to save and load feature definitions, even in production environment?
    `with gzip.GzipFile('ft_feas.pkl.gzip', "rb") as f: feas = pkl.load(f)`
    <details>
    ---------------------------------------------------------------------------
    ModuleNotFoundError                       Traceback (most recent call last)
    <ipython-input-5-eff837b8f89c> in <module>
    ----> 1 with gzip.GzipFile('ft_feas_def.pkl.gzip', "rb") as f: feas = pkl.load(f)

    ModuleNotFoundError: No module named 'xx-feas'
    </details>

Any ideas would be highly appreciated. Best regards!

**Comment by thehomebrewnerd** [comment]
@dehiker You should save the feature definitions and reload them using the built-in feature serialization methods `save_features` and `load_features`. See the [API Reference](https://featuretools.alteryx.com/en/stable/api_reference.html#saving-and-loading-features) for more details. 

When the feature definitions are loaded in, the module in which they are defined also needs to be present. The feature needs to have access to the primitive definition code to properly recreate the feature and access the primitive function.

For your first question, it appears to me to be a problem with the datatypes - are you trying to calculate median on a string column? I would start by confirming that all of the dtype in your second chunk match the dtypes used when you created the feature definitions.

**Comment by dehiker** [comment]
Thank you @thehomebrewnerd 

>  are you trying to calculate median on a string column?

I got features definitions when DFS for the first chunk, and apply it to the second chunk. I found no idea why this could happen.

> feature serialization methods `save_features` and `load_features`

Do you know if I could save features of different training_windows to ONE file, or I should save to features of different training_windows to separate files? I found, for example for Count primitive, features of different training_windows seems like the same.

**Comment by thehomebrewnerd** [comment]
> I got features definitions when DFS for the first chunk, and apply it to the second chunk. I found no idea why this could happen.

This could happen if your data is not uniform across chunks and you don't specify the column types when you create an EntitySet for each chunk. If you don't specify the logical types, they will be inferred and data differences between chunks can result in different inferred logical types. Can you check the Woodwork logical types and confirm that the types in the second chunk are the same as the types in the first chunk using `es["your_dataframe_name"].ww.logical_types`?

> Do you know if I could save features of different training_windows to ONE file, or I should save to features of different training_windows to separate files?

You should be able to use the same feature definitions for multiple `training_window` values. The `training_window` value is used when calculating the feature values, not when creating the `Feature` object definitions.

**Comment by dehiker** [comment]
Mang thanks for your helpful info @thehomebrewnerd 

I'll check logical_types next time. But it's kinda strange that no error shown when I re-ran the code.

I'll close this issue, and get back here if necessary. Thank you again sincerely!

**Comment by thehomebrewnerd** [comment]
> I suspect it's because values of some id columns also saved, even the columns is set in, such as ignore_columns={'df': ['id0', 'id1']}. Is it possible to skip them when save_features?

@dehiker There is no way to customize what gets saved in the JSON. Featuretools should only be saving the information needed to reconstruct the Feature objects upon deserialization, but we can take a look and make sure there isn't any extra information getting stored unnecessarily.

**Comment by thehomebrewnerd** [comment]
@dehiker Going to close this our for now, but feel free to reopen or create a new issue if you have additional questions.
